package rule

import "github.com/Pimatis/mavetis/src/model"

func authorize() []model.Rule {
	return []model.Rule{
		{
			ID:          "auth.role.deleted",
			Title:       "Authorization role check removed",
			Message:     "A probable role or permission enforcement check was removed from the diff.",
			Remediation: "Restore the deleted role check or add an equivalent permission validation before the protected action.",
			Category:    "authorization",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(requireRole|hasRole|authorize|permission|rbac|scope|can\()`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-Authorization"),
		},
		{
			ID:          "auth.owner.deleted",
			Title:       "Ownership or tenant check removed",
			Message:     "A probable ownership, organization, or tenant isolation check was removed from the diff.",
			Remediation: "Restore tenant and ownership validation before the resource lookup or mutation executes.",
			Category:    "authorization",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(owner|ownership|tenant|organization|orgId|workspace|accountId|belongsTo)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-Authorization"),
		},
		{
			ID:          "authorization.scope.deleted",
			Title:       "Tenant or resource scope filter removed",
			Message:     "The diff removes a query or filter fragment that appears to scope access by tenant, account, or owner.",
			Remediation: "Restore the scoping predicate so resource reads and writes remain bound to the caller's authorization context.",
			Category:    "authorization",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(tenant(_id)?|org(_id)?|workspace(_id)?|account(_id)?|owner(_id)?|user(_id)?)`},
			Near:        []string{`(?i)(where|filter|query|select|find|first|delete|update)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-Authorization"),
		},
		{
			ID:          "authorization.bypass.added",
			Title:       "Authorization bypass flag introduced",
			Message:     "The diff introduces a probable authorization bypass or allow-all policy flag.",
			Remediation: "Remove the bypass and preserve deny-by-default authorization decisions for protected operations.",
			Category:    "authorization",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(skipAuthoriz|disableAuthoriz|allowAll|permitAll|allowAnonymous|authorization\s*[:=]\s*false|rbac\s*[:=]\s*false)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-Authorization"),
		},
		{
			ID:          "authorization.idor.lookup",
			Title:       "Direct object lookup introduced without nearby ownership signals",
			Message:     "The diff introduces an object lookup from request-controlled identifiers without nearby tenant, owner, or permission signals.",
			Remediation: "Bind resource lookups to the caller's tenant, owner, or permission context before returning or mutating objects.",
			Category:    "authorization",
			Severity:    "high",
			Confidence:  "low",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(params\.|query\.|ctx\.Params|ctx\.Query|request\.(params|query)|URLParam|mux\.Vars).{0,30}(id|userId|accountId|orgId|projectId|conversationId)`},
			Near:        []string{`(?i)(find|first|get|load|select|query|delete|update)`},
			Absent:      []string{`(?i)(owner|tenant|org|workspace|account|permission|authorize|requireRole|scope|policy)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-Authorization"),
		},
		{
			ID:          "authorization.operation.deleted",
			Title:       "Operation-level permission check removed",
			Message:     "The diff removes a permission check tied to a sensitive action such as read, update, delete, or manage.",
			Remediation: "Restore operation-level authorization for the affected action before executing the request.",
			Category:    "authorization",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(can(Read|Write|Update|Delete|Manage)|hasPermission|authorize.*(read|write|update|delete|manage)|permission.*(read|write|update|delete|manage))`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-Authorization"),
		},
	}
}
