package rule

import "github.com/Pimatis/mavetis/src/model"

func authn() []model.Rule {
	return []model.Rule{
		{
			ID:          "auth.middleware.deleted",
			Title:       "Authentication middleware removed",
			Message:     "A probable authentication middleware or guard was removed from the diff.",
			Remediation: "Restore the guard or replace it with an equivalent access control enforcement path.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(auth|authenticate|middleware|guard|requireAuth|verifySession|isAuthenticated)`},
			Standards:   standard("OWASP-ASVS-V3.1", "OWASP-Authentication"),
		},
		{
			ID:          "session.storage.local",
			Title:       "Token persisted in local storage",
			Message:     "The diff stores authentication material in browser local storage.",
			Remediation: "Prefer HttpOnly secure cookies or platform-backed secure storage for bearer tokens.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       webFiles(),
			Require:     []string{`(?i)localStorage\.(setItem|getItem).*?(token|jwt|session|auth)`},
			Standards:   standard("OWASP-ASVS-V3.4", "OWASP-Authentication"),
		},
		{
			ID:          "token.decode.only",
			Title:       "JWT decode used without verification",
			Message:     "The diff introduces token decoding instead of signature verification.",
			Remediation: "Verify token signatures and claims before use instead of decoding untrusted tokens directly.",
			Category:    "token",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(jwt\.|token\.)decode\(`},
			Absent:      []string{`(?i)(verify|parseWithClaims|validate|CheckSignature)`},
			Standards:   standard("OWASP-ASVS-V3.5", "OWASP-Authentication"),
		},
		{
			ID:          "auth.bypass.debug",
			Title:       "Authentication bypass flag introduced",
			Message:     "The diff introduces a probable authentication bypass or anonymous override flag.",
			Remediation: "Remove the bypass and keep authentication decisions explicit, deny-by-default, and environment-independent.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(skipAuth|disableAuth|authDisabled|allowAnonymous|anonymousAccess|requireAuth\s*[:=]\s*false)`},
			Standards:   standard("OWASP-ASVS-V3.1", "OWASP-Authentication"),
		},
		{
			ID:          "auth.password.plaintext",
			Title:       "Plaintext password comparison introduced",
			Message:     "The diff compares passwords or credentials with a plaintext equality check instead of a secure hash comparison.",
			Remediation: "Store passwords with a modern hashing algorithm and use a constant-time comparison primitive for verification.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(password|passwd|pwd).{0,20}(==|===|!=|!==|equals\()`},
			Absent:      []string{`(?i)(bcrypt|argon2|scrypt|pbkdf2|compareHash|subtle|constantTime)`},
			Standards:   standard("OWASP-ASVS-V2.4", "OWASP-Authentication"),
		},
		{
			ID:          "auth.password.weakhash",
			Title:       "Weak password hashing introduced",
			Message:     "The diff hashes passwords with a fast or weak digest algorithm instead of an adaptive hashing function.",
			Remediation: "Use an adaptive password hashing function such as bcrypt, argon2, scrypt, or PBKDF2 with appropriate work factors.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(md5|sha1|sha256|sha512)\b.*?\(.*?(password|passwd|pwd|credential)`},
			Absent:      []string{`(?i)(bcrypt|argon2|scrypt|pbkdf2)`},
			Standards:   standard("OWASP-ASVS-V2.4", "OWASP-ASVS-V6.2", "OWASP-Authentication"),
		},
		{
			ID:          "auth.reset.token.logged",
			Title:       "Password reset token logging introduced",
			Message:     "The diff logs password reset or recovery token material.",
			Remediation: "Never log reset tokens; emit only non-sensitive request identifiers and keep recovery tokens single-use and short-lived.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|logger\.|console\.|print\(|fmt\.(Print|Printf)).*(reset|recovery|forgot|magic.?link).*(token|code|secret)`},
			Standards:   standard("OWASP-ASVS-V2.1", "OWASP-ASVS-V8.1", "OWASP-Authentication"),
			Mask:        true,
		},
		{
			ID:          "auth.password.change.without.current",
			Title:       "Password change without current password or reauth signal",
			Message:     "The diff introduces password update logic without nearby current-password, MFA, or reauthentication checks.",
			Remediation: "Require current password verification, MFA, or fresh reauthentication before changing account credentials.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(update|change|set).{0,24}(password|passwd|pwd)`},
			Near:        []string{`(?i)(user|account|credential|profile)`},
			Absent:      []string{`(?i)(currentPassword|oldPassword|verifyPassword|reauth|mfa|totp|webauthn|recentLogin)`},
			Standards:   standard("OWASP-ASVS-V2.1", "OWASP-Authentication"),
		},
		{
			ID:          "auth.hardcoded.credentials",
			Title:       "Hardcoded credential introduced",
			Message:     "The diff introduces a hardcoded password, API key, or secret in source code.",
			Remediation: "Move secrets to a secure vault, environment variables, or encrypted configuration and rotate any exposed values.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(password|passwd|pwd|api[_-]?key|secret|token)\s*[:=]\s*["\'][A-Za-z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]{8,}["\']`},
			Absent:      []string{`(?i)(os\.Getenv|process\.env|vault|secrets?manager|config\.get|env\.)`},
			Standards:   standard("OWASP-ASVS-V2.4", "OWASP-ASVS-V6.4", "OWASP-Authentication"),
			Mask:        true,
		},
		{
			ID:          "auth.apikey.inurl",
			Title:       "API key in URL query parameter introduced",
			Message:     "The diff passes an API key or token through a URL query parameter.",
			Remediation: "Move credentials to headers or secure cookies and avoid exposing them in URLs that may be logged or shared.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(api[_-]?key|token|secret|access[_-]?key)\s*=\s*[^&\s]+`},
			Standards:   standard("OWASP-ASVS-V3.5", "OWASP-Authentication"),
			Mask:        true,
		},
		{
			ID:          "auth.basic.overhttp",
			Title:       "Basic authentication over plain HTTP",
			Message:     "The diff sends Basic authentication credentials over an unencrypted HTTP connection.",
			Remediation: "Require TLS for all Basic authentication flows and reject plaintext transport.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(Authorization:\s*Basic|auth\(.*basic|basic\s*auth)`},
			Near:        []string{`(?i)(http://|req\.protocol\s*===?\s*['"]http['"])`},
			Absent:      []string{`(?i)(https://|tls|ssl|redirectToHttps)`},
			Standards:   standard("OWASP-ASVS-V2.4", "OWASP-ASVS-V9.1", "OWASP-Authentication"),
		},
		{
			ID:          "auth.weak.policy",
			Title:       "Weak password policy introduced",
			Message:     "The diff configures a password policy with weak requirements.",
			Remediation: "Enforce a strong password policy with minimum length, complexity, and history requirements.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(minLength|min_len|password_policy|passwordPolicy).{0,10}(=|:).{0,10}(\d)`},
			Standards:   standard("OWASP-ASVS-V2.1", "OWASP-Authentication"),
		},
		{
			ID:          "auth.enumeration",
			Title:       "Account enumeration risk introduced",
			Message:     "The diff returns different error messages for existing and non-existing accounts.",
			Remediation: "Return a single generic message for all authentication failures to prevent username enumeration.",
			Category:    "auth",
			Severity:    "medium",
			Confidence:  "low",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(user not found|invalid user|wrong password|password incorrect|account does not exist)`},
			Standards:   standard("OWASP-ASVS-V2.1", "OWASP-Authentication"),
		},
	}
}
