package rule

import "github.com/Pimatis/mavetis/src/model"

func cloud() []model.Rule {
	return []model.Rule{
		{
			ID:          "cloud.storage.public.read",
			Title:       "Public object storage read access introduced",
			Message:     "The diff grants public read access to object storage data.",
			Remediation: "Keep buckets private by default and expose objects through authenticated or tightly scoped delivery paths.",
			Category:    "cloud",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(public-read|allUsers|allAuthenticatedUsers|Principal\s*[:=]\s*["']\*["']|AllowPublicRead|blockPublicAcls\s*[:=]\s*false)`},
			Near:        []string{`(?i)(bucket|storage|s3|gcs|r2|blob|object)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Cloud"),
		},
		{
			ID:          "cloud.storage.public.write",
			Title:       "Public object storage write access introduced",
			Message:     "The diff grants public write access to object storage data.",
			Remediation: "Disallow public writes and require authenticated, authorized uploads with content validation.",
			Category:    "cloud",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(public-read-write|WRITE_ACP|s3:PutObject|storage\.objects\.create|blobServices/write|allUsers)`},
			Near:        []string{`(?i)(bucket|storage|s3|gcs|r2|blob|object|upload)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Cloud"),
		},
		{
			ID:          "cloud.storage.presigned.longlived",
			Title:       "Long-lived presigned storage URL introduced",
			Message:     "The diff creates a presigned object storage URL with a long validity period.",
			Remediation: "Keep presigned URLs short-lived and bind them to the minimum operation and object scope required.",
			Category:    "cloud",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(presign|presigned|SignedURL|GeneratePresignedUrl|getSignedUrl).*(24\s*\*\s*time\.Hour|7\s*\*\s*24|604800|86400|time\.Hour\s*\*\s*(24|48|72))`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Cloud"),
		},
		{
			ID:          "iac.iam.policy.wildcard",
			Title:       "Wildcard IAM policy introduced",
			Message:     "The diff grants wildcard cloud IAM actions or resources.",
			Remediation: "Replace wildcard IAM permissions with explicit actions and resources required by the workload.",
			Category:    "cloud",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)["']?(Action|Resource|NotAction|NotResource)["']?\s*[:=]\s*(\[\s*)?["']\*["']`},
			Near:        []string{`(?i)(iam|policy|statement|role|principal|["']?Effect["']?\s*[:=]\s*["']Allow)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Cloud"),
		},
		{
			ID:          "iac.securitygroup.open.ssh",
			Title:       "Public SSH ingress introduced",
			Message:     "The diff opens SSH ingress to the public internet.",
			Remediation: "Restrict SSH to approved administrative networks or remove direct SSH exposure entirely.",
			Category:    "cloud",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(0\.0\.0\.0/0|::/0|cidr_blocks\s*=\s*\[\s*["']0\.0\.0\.0/0["']).*(22|ssh)|(22|ssh).*(0\.0\.0\.0/0|::/0)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Cloud"),
		},
		{
			ID:          "cloud.db.public",
			Title:       "Public database access introduced",
			Message:     "The diff exposes a managed database to the public internet.",
			Remediation: "Restrict database access to private subnets and approved bastion hosts.",
			Category:    "cloud",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(publicly_accessible\s*=\s*true|0\.0\.0\.0/0).*(3306|5432|1433|27017|6379|11211)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Cloud"),
		},
	}
}
