package rule

import "github.com/Pimatis/mavetis/src/model"

func crypto() []model.Rule {
	return []model.Rule{
		{
			ID:          "crypto.mathrandom",
			Title:       "Weak random source introduced",
			Message:     "The diff introduces a weak randomness source for security-sensitive code.",
			Remediation: "Use a cryptographically secure randomness source for tokens, keys, nonces, and IVs.",
			Category:    "crypto",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(Math\.random\(|rand\.(Seed|Int|Read)\()|random\.random\(`},
			Near:        []string{`(?i)(token|secret|nonce|iv|password|key|session|otp|code)`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.staticiv",
			Title:       "Static IV or nonce introduced",
			Message:     "The diff appears to introduce a hard-coded IV or nonce.",
			Remediation: "Generate a fresh unpredictable IV or nonce for every encryption operation.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(iv|nonce).{0,10}[=:].{0,5}["'][A-Za-z0-9+/=_-]{8,}["']`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.weakhash",
			Title:       "Weak hash algorithm introduced",
			Message:     "The diff introduces a weak hash algorithm for security-sensitive use.",
			Remediation: "Use a modern password hashing or message digest strategy appropriate for the context.",
			Category:    "crypto",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(md5|sha1)\(`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.weakcipher",
			Title:       "Weak cipher or insecure mode introduced",
			Message:     "The diff introduces a weak cipher primitive or an insecure cipher mode such as ECB.",
			Remediation: "Use modern authenticated encryption or other approved primitives with secure modes and key sizes.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(\bDES\b|3DES|RC4|MODE_ECB|ECBMode|aes-128-ecb|des-ede3|NewTripleDESCipher)`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.custom",
			Title:       "Custom cryptography routine introduced",
			Message:     "The diff appears to implement custom cryptographic transformations.",
			Remediation: "Prefer vetted standard library cryptographic primitives and established protocols over custom routines.",
			Category:    "crypto",
			Severity:    "medium",
			Confidence:  "low",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(xorEncrypt|customEncrypt|rollYourOwn|obfuscateKey|homegrown)`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.compare.missing",
			Title:       "Non constant-time secret comparison introduced",
			Message:     "The diff compares secrets with a standard equality check.",
			Remediation: "Use a constant-time comparison primitive for secrets, signatures, and MACs.",
			Category:    "crypto",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)((signature|hmac|secret|token|digest|mac).{0,20}(==|===|!=|!==).{0,20}(signature|hmac|secret|token|digest|mac))|((signature|hmac|secret|token).{0,20}equals\()`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.key.exposed",
			Title:       "Key material exposure introduced",
			Message:     "The diff logs, returns, or serializes private key or secret key material.",
			Remediation: "Keep key material in protected memory only and never expose it through logs, responses, or debug output.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|print\(|return|respond|json\.|fmt\.).*(private.?key|secret.?key|signing.?key|hmac.?key)`},
			Standards:   standard("OWASP-ASVS-V6.4", "OWASP-Crypto"),
			Mask:        true,
		},
		{
			ID:          "crypto.alg.none",
			Title:       "Unsigned token or algorithm none acceptance introduced",
			Message:     "The diff accepts unsigned tokens or configures the algorithm to none.",
			Remediation: "Reject unsigned tokens and restrict verification to explicit strong algorithms.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(alg\s*[:=]\s*["']none["']|algorithm\s*[:=]\s*["']none["']|acceptUnverified|allowUnsigned)`},
			Standards:   standard("OWASP-ASVS-V3.5", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.verify.skip",
			Title:       "Signature or certificate verification bypass introduced",
			Message:     "The diff appears to bypass signature, certificate, or token verification.",
			Remediation: "Preserve verification failures as hard errors and validate trust anchors explicitly.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(skipVerify|verify\s*[:=]\s*false|ignoreSignature|acceptInvalid|InsecureSkipVerify)`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.verify.deleted",
			Title:       "Signature verification removed",
			Message:     "The diff removes a probable signature, MAC, or token verification step.",
			Remediation: "Restore verification before trusting the artifact, payload, or peer.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(verify|checkSignature|validateSignature|ParseWithClaims|rsa\.Verify|ecdsa\.Verify|hmac\.Equal)`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
		{
			ID:          "crypto.rsa.keysize",
			Title:       "Inadequate RSA key size introduced",
			Message:     "The diff generates or configures an RSA key with a size below the recommended minimum.",
			Remediation: "Use at least 2048-bit RSA keys and prefer 3072-bit or higher for long-term protection.",
			Category:    "crypto",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)rsa\.GenerateKey\([^,]+,\s*(512|768|1024)\)|rsa_key_size\s*[:=]\s*(512|768|1024)|rsakeysize\s*[:=]\s*(512|768|1024)|rsaKeySize\s*[:=]\s*(512|768|1024)`},
			Standards:   standard("OWASP-ASVS-V6.2", "OWASP-Crypto"),
		},
	}
}
