package rule

import "github.com/Pimatis/mavetis/src/model"

func drift() []model.Rule {
	paths := append(configFiles(), deploymentFiles()...)
	return []model.Rule{
		{
			ID:          "config.debug.enabled",
			Title:       "Debug mode enabled in executable configuration",
			Message:     "The diff enables debug behavior in configuration or runtime settings that look production-bound.",
			Remediation: "Keep debug features disabled in production-facing environments and gate diagnostics behind protected internal workflows.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(^|\s)(debug|app_debug|debug_mode)\s*[:=]\s*(true|1|on)|debug\s*:\s*true`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Config"),
		},
		{
			ID:          "config.env.production",
			Title:       "Production environment downgraded or weakened",
			Message:     "The diff introduces a non-production runtime mode or fallback in a path that looks production-relevant.",
			Remediation: "Keep production mode explicit and avoid development or local fallbacks in deployable runtime configuration.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(node_env|app_env|environment)\s*[:=]\s*["']?(development|dev|test|local)["']?|process\.env\.NODE_ENV\s*\|\|\s*["'](development|dev|test|local)["']`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Config"),
		},
		{
			ID:          "config.cors.wildcard",
			Title:       "Wildcard CORS origin introduced in configuration",
			Message:     "The diff enables a wildcard origin in configuration, which can widen browser trust unexpectedly.",
			Remediation: "Use explicit trusted origins and keep cross-origin policy reviewable in deployable configuration.",
			Category:    "cors",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(cors|origin|allow-origin|allowed_origins|allowedOrigins).{0,40}(\*|"\*"|'\*')|access-control-allow-origin\s*[:=]\s*\*`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-CORS"),
		},
		{
			ID:          "config.csp.disabled",
			Title:       "Content Security Policy disabled or weakened",
			Message:     "The diff disables CSP or introduces policy values that materially weaken script execution controls.",
			Remediation: "Keep CSP enabled and avoid unsafe-inline or unsafe-eval in production policies unless a reviewed exception exists.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(disableCSP|csp\s*[:=]\s*false|contentSecurityPolicy\s*[:=]\s*false|content-security-policy.*(unsafe-inline|unsafe-eval)|csp_header\s*off)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-CSP"),
		},
		{
			ID:          "config.tls.legacy",
			Title:       "Legacy TLS or HTTPS enforcement downgrade introduced",
			Message:     "The diff lowers TLS expectations or disables HTTPS-only behavior in deployable configuration.",
			Remediation: "Require modern TLS versions and keep HTTPS enforcement enabled for production-facing services.",
			Category:    "transport",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(tlsv1(\.0|\.1)?|versiontls10|versiontls11|min[_-]?tls\s*[:=]\s*1\.[01]|ssl_protocols\s+tlsv1|httpsOnly\s*[:=]\s*false|force_ssl\s+off|ssl_redirect\s*[:=]\s*false)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Transport"),
		},
		{
			ID:          "config.container.privileged",
			Title:       "Privileged container execution introduced",
			Message:     "The diff enables privileged container or overly broad capability settings in deployable configuration.",
			Remediation: "Run containers with the minimum privileges required and avoid privileged mode or ALL capabilities.",
			Category:    "config",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       deploymentFiles(),
			Require:     []string{`(?i)(privileged\s*[:=]\s*true|cap_add\s*:\s*\[?\s*ALL|allowPrivilegeEscalation\s*[:=]\s*true|securityContext\s*:.*privileged\s*:\s*true)`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Container"),
		},
	}
}
