package rule

import "github.com/Pimatis/mavetis/src/model"

func drift() []model.Rule {
	paths := append(configFiles(), deploymentFiles()...)
	return []model.Rule{
		{
			ID:          "config.debug.enabled",
			Title:       "Debug mode enabled in executable configuration",
			Message:     "The diff enables debug behavior in configuration or runtime settings that look production-bound.",
			Remediation: "Keep debug features disabled in production-facing environments and gate diagnostics behind protected internal workflows.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(^|\s)(debug|app_debug|debug_mode)\s*[:=]\s*(true|1|on)|debug\s*:\s*true`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Config"),
		},
		{
			ID:          "config.env.production",
			Title:       "Production environment downgraded or weakened",
			Message:     "The diff introduces a non-production runtime mode or fallback in a path that looks production-relevant.",
			Remediation: "Keep production mode explicit and avoid development or local fallbacks in deployable runtime configuration.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(node_env|app_env|environment)\s*[:=]\s*["']?(development|dev|test|local)["']?|process\.env\.NODE_ENV\s*\|\|\s*["'](development|dev|test|local)["']`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Config"),
		},
		{
			ID:          "config.cors.wildcard",
			Title:       "Wildcard CORS origin introduced in configuration",
			Message:     "The diff enables a wildcard origin in configuration, which can widen browser trust unexpectedly.",
			Remediation: "Use explicit trusted origins and keep cross-origin policy reviewable in deployable configuration.",
			Category:    "cors",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(cors|origin|allow-origin|allowed_origins|allowedOrigins).{0,40}(\*|"\*"|'\*')|access-control-allow-origin\s*[:=]\s*\*`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-CORS"),
		},
		{
			ID:          "config.csp.disabled",
			Title:       "Content Security Policy disabled or weakened",
			Message:     "The diff disables CSP or introduces policy values that materially weaken script execution controls.",
			Remediation: "Keep CSP enabled and avoid unsafe-inline or unsafe-eval in production policies unless a reviewed exception exists.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(disableCSP|csp\s*[:=]\s*false|contentSecurityPolicy\s*[:=]\s*false|content-security-policy.*(unsafe-inline|unsafe-eval)|csp_header\s*off)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-CSP"),
		},
		{
			ID:          "config.tls.legacy",
			Title:       "Legacy TLS or HTTPS enforcement downgrade introduced",
			Message:     "The diff lowers TLS expectations or disables HTTPS-only behavior in deployable configuration.",
			Remediation: "Require modern TLS versions and keep HTTPS enforcement enabled for production-facing services.",
			Category:    "transport",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(tlsv1(\.0|\.1)?|versiontls10|versiontls11|min[_-]?tls\s*[:=]\s*1\.[01]|ssl_protocols\s+tlsv1|httpsOnly\s*[:=]\s*false|force_ssl\s+off|ssl_redirect\s*[:=]\s*false)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Transport"),
		},
		{
			ID:          "config.container.privileged",
			Title:       "Privileged container execution introduced",
			Message:     "The diff enables privileged container or overly broad capability settings in deployable configuration.",
			Remediation: "Run containers with the minimum privileges required and avoid privileged mode or ALL capabilities.",
			Category:    "config",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       deploymentFiles(),
			Require:     []string{`(?i)(privileged\s*[:=]\s*true|cap_add\s*:\s*\[?\s*ALL|allowPrivilegeEscalation\s*[:=]\s*true|securityContext\s*:.*privileged\s*:\s*true)`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Container"),
		},
		{
			ID:          "config.hsts.missing",
			Title:       "HSTS header missing or disabled",
			Message:     "The diff removes or omits HTTP Strict Transport Security headers in a production-relevant configuration.",
			Remediation: "Enable HSTS with a long max-age and includeSubDomains in production-facing services.",
			Category:    "transport",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(hsts\s*[:=]\s*false|disableHSTS|strict-transport-security\s*[:=]\s*false|X-STS-Protection\s*[:=]\s*0)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Transport"),
		},
		{
			ID:          "config.xframe.missing",
			Title:       "X-Frame-Options or frame-ancestors protection missing",
			Message:     "The diff removes or weakens clickjacking protection in a production-relevant configuration.",
			Remediation: "Set X-Frame-Options to DENY or SAMEORIGIN, or use CSP frame-ancestors to control framing.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(xframe\s*[:=]\s*false|disableXFrame|X-Frame-Options\s*[:=]\s*false|frame-ancestors\s*[:=]\s*\*|allowFrom\s*[:=]\s*\*)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Clickjacking"),
		},
		{
			ID:          "config.xcontenttype.missing",
			Title:       "X-Content-Type-Options protection missing",
			Message:     "The diff removes or disables MIME-type sniffing protection in a production-relevant configuration.",
			Remediation: "Set X-Content-Type-Options to nosniff to prevent MIME-type sniffing attacks.",
			Category:    "config",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(xcontenttype\s*[:=]\s*false|disableXContentType|X-Content-Type-Options\s*[:=]\s*false|nosniff\s*[:=]\s*false)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Config"),
		},
		{
			ID:          "config.referrer.unsafe",
			Title:       "Unsafe Referrer-Policy introduced",
			Message:     "The diff sets an overly permissive Referrer-Policy.",
			Remediation: "Use strict-origin-when-cross-origin or no-referrer to reduce referrer leakage.",
			Category:    "config",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(Referrer-Policy\s*[:=]\s*["\']?unsafe-url["\']?|referrerPolicy\s*[:=]\s*["\']?unsafe-url["\']?)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Config"),
		},
		{
			ID:          "config.permissions.wildcard",
			Title:       "Overly permissive Permissions-Policy introduced",
			Message:     "The diff sets a wildcard or overly broad Permissions-Policy.",
			Remediation: "Explicitly allow only the required features and deny the rest.",
			Category:    "config",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(Permissions-Policy|permissions-policy).{0,20}\*`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Config"),
		},
		{
			ID:          "config.csp.wildcard",
			Title:       "CSP script-src or style-src wildcard introduced",
			Message:     "The diff allows any source for scripts or styles through a CSP wildcard.",
			Remediation: "Use strict source lists and avoid wildcards in script-src and style-src directives.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(script-src|style-src|default-src).{0,20}\*`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-CSP"),
		},
		{
			ID:          "config.csp.frameancestors.wildcard",
			Title:       "CSP frame-ancestors wildcard introduced",
			Message:     "The diff allows any origin to frame the application through a CSP wildcard.",
			Remediation: "Use frame-ancestors 'none' or an explicit allowlist of trusted origins.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       paths,
			Require:     []string{`(?i)(frame-ancestors).{0,20}\*`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-CSP"),
		},
		{
			ID:          "config.sri.missing",
			Title:       "Subresource Integrity missing",
			Message:     "The diff loads external scripts or stylesheets without an integrity attribute.",
			Remediation: "Add integrity hashes to all externally loaded scripts and stylesheets.",
			Category:    "config",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       webFiles(),
			Require:     []string{`(?i)(<script\s+src|<link\s+href).{0,200}>`},
			Absent:      []string{`(?i)(integrity=)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Config"),
		},
		{
			ID:          "config.container.root",
			Title:       "Container running as root introduced",
			Message:     "The diff configures a container to run as root.",
			Remediation: "Run containers as a non-root user and drop unnecessary capabilities.",
			Category:    "config",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       deploymentFiles(),
			Require:     []string{`(?i)(USER\s+root|runAsUser:\s*0|runAsRoot:\s*true)`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Container"),
		},
		{
			ID:          "config.k8s.hostnetwork",
			Title:       "Kubernetes hostNetwork enabled",
			Message:     "The diff enables hostNetwork on a Kubernetes pod.",
			Remediation: "Disable hostNetwork unless the workload strictly requires direct host networking.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       deploymentFiles(),
			Require:     []string{`(?i)(hostNetwork:\s*true)`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Container"),
		},
		{
			ID:          "config.k8s.secrets.env",
			Title:       "Kubernetes Secret exposed as environment variable",
			Message:     "The diff mounts a Kubernetes Secret into a container as an environment variable.",
			Remediation: "Mount secrets as files rather than environment variables to reduce exposure.",
			Category:    "config",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       deploymentFiles(),
			Require:     []string{`(?i)(secretKeyRef|valueFrom:\s*secretKeyRef)`},
			Standards:   standard("OWASP-ASVS-V14.4", "OWASP-Secrets"),
		},
		{
			ID:          "config.k8s.nosecuritycontext",
			Title:       "Kubernetes container missing securityContext",
			Message:     "The diff adds a container without a securityContext.",
			Remediation: "Define a securityContext for every container with runAsNonRoot, readOnlyRootFilesystem, and dropped capabilities.",
			Category:    "config",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       deploymentFiles(),
			Require:     []string{`(?i)(containers:)`},
			Absent:      []string{`(?i)(securityContext)`},
			Standards:   standard("OWASP-ASVS-V1.14", "OWASP-Container"),
		},
		{
			ID:          "config.db.ssl.disabled",
			Title:       "Database SSL/TLS disabled",
			Message:     "The diff disables SSL/TLS for a database connection.",
			Remediation: "Require TLS for all database connections and verify server certificates.",
			Category:    "config",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(sslmode\s*=\s*disable|useSSL\s*=\s*false|tls\s*=\s*false|rejectUnauthorized\s*=\s*false)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Config"),
		},
		{
			ID:          "config.db.publickey",
			Title:       "MySQL allowPublicKeyRetrieval enabled",
			Message:     "The diff enables allowPublicKeyRetrieval for a MySQL connection.",
			Remediation: "Disable allowPublicKeyRetrieval and use a secure TLS connection instead.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(allowPublicKeyRetrieval\s*=\s*true)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Config"),
		},
		{
			ID:          "config.redis.noauth",
			Title:       "Redis connection without authentication",
			Message:     "The diff connects to Redis without a password or TLS.",
			Remediation: "Enable Redis AUTH and require TLS for remote connections.",
			Category:    "config",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(redis\.NewClient|redis\.Dial|NewRedis|redis://)`},
			Absent:      []string{`(?i)(Password|TLSConfig|tls|auth)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Config"),
		},
	}
}
