package rule

import "github.com/Pimatis/mavetis/src/model"

func inject() []model.Rule {
	return []model.Rule{
		{
			ID:          "inject.sql.raw",
			Title:       "Raw SQL query introduced",
			Message:     "The diff introduces string-built SQL that may bypass parameterization.",
			Remediation: "Use parameterized queries or prepared statements for dynamic SQL input.",
			Category:    "injection",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)\b(select\b.+\bfrom\b|insert\b.+\binto\b|update\b.+\bset\b|delete\b.+\bfrom\b).*(\+|fmt\.|sprintf|f"|\$\{|%s)`},
			Standards:   standard("OWASP-ASVS-V1.2", "OWASP-SQL"),
		},
		{
			ID:          "inject.command.exec",
			Title:       "Command execution introduced",
			Message:     "The diff introduces shell or command execution with probable untrusted input flow.",
			Remediation: "Avoid shell execution where possible and strictly separate arguments from user input.",
			Category:    "injection",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(exec\(|spawn\(|system\(|Runtime\.getRuntime\(|subprocess\.|sh\s+-c|bash\s+-c)`},
			Near:        []string{`(?i)(input|param|query|body|request|user|argv)`},
			Standards:   standard("OWASP-ASVS-V1.2", "OWASP-Injection"),
		},
		{
			ID:          "inject.ssrf.fetch",
			Title:       "External fetch based on untrusted input introduced",
			Message:     "The diff introduces a probable SSRF sink using untrusted URLs.",
			Remediation: "Resolve remote targets through a strict allowlist and block private, loopback, and metadata endpoints.",
			Category:    "ssrf",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(fetch\(|http\.Get\(|http\.Post\(|axios\.|requests\.(get|post)|urllib|urlopen\()`},
			Near:        []string{`(?i)(url|uri|target|endpoint|request|query|param|input)`},
			Absent:      []string{`(?i)(allowlist|whitelist|isAllowedHost|isTrustedHost|privateRange|linklocal|metadata|169\.254\.169\.254|127\.0\.0\.1|localhost)`},
			Standards:   standard("OWASP-ASVS-V4.3", "OWASP-SSRF"),
		},
		{
			ID:          "inject.xss.innerhtml",
			Title:       "Unsafe HTML sink introduced",
			Message:     "The diff introduces innerHTML or a comparable unsafe HTML rendering sink.",
			Remediation: "Use safe DOM APIs, context-aware encoding, or framework sanitization primitives.",
			Category:    "xss",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       webFiles(),
			Require:     []string{`(?i)(innerHTML|dangerouslySetInnerHTML|v-html|unsafeHTML)`},
			Standards:   standard("OWASP-ASVS-V3.2", "OWASP-XSS"),
		},
		{
			ID:          "inject.deserialize",
			Title:       "Unsafe deserialization introduced",
			Message:     "The diff introduces a deserialization flow that may trust attacker-controlled data.",
			Remediation: "Avoid native object deserialization for untrusted input and validate payload shape before use.",
			Category:    "deserialization",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(pickle\.loads|yaml\.load\(|gob\.NewDecoder|BinaryFormatter|deserialize\()`},
			Standards:   standard("OWASP-ASVS-V1.5", "OWASP-Deserialization"),
		},
		{
			ID:          "inject.traversal",
			Title:       "Path traversal risk introduced",
			Message:     "The diff introduces filesystem access using path fragments that may be attacker-controlled.",
			Remediation: "Normalize, bound, and validate filesystem paths before opening or writing files.",
			Category:    "file",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(ReadFile|WriteFile|os\.Open|os\.OpenFile|filepath\.Join|path\.Join|os\.Create)`},
			Near:        []string{`(?i)(\.\./|filename|filepath|path|request|query|param|input)`},
			Absent:      []string{`(?i)(filepath\.Clean|path\.Clean|filepath\.Base|safeJoin|EvalSymlinks)`},
			Standards:   standard("OWASP-ASVS-V5.4", "OWASP-File"),
		},
		{
			ID:          "inject.upload.validation",
			Title:       "File upload introduced without validation signals",
			Message:     "The diff introduces file upload handling without obvious content validation or storage controls.",
			Remediation: "Validate MIME type, extension, size, storage path, and scanning requirements before accepting uploads.",
			Category:    "file",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(multipart|FormFile|IFormFile|request\.files|UploadFile|ParseMultipartForm)`},
			Near:        []string{`(?i)(save|write|copy|store|upload)`},
			Absent:      []string{`(?i)(mime|content-type|extension|signature|magic|scan|sanitize|size\s*(limit|max)|maxUpload)`},
			Standards:   standard("OWASP-ASVS-V5.2", "OWASP-File"),
		},
		{
			ID:          "inject.tls.disable",
			Title:       "TLS verification disabled",
			Message:     "The diff disables TLS verification for outbound connections.",
			Remediation: "Keep TLS verification enabled and pin trust only when a documented exception exists.",
			Category:    "transport",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(InsecureSkipVerify\s*:\s*true|rejectUnauthorized\s*:\s*false|verify\s*=\s*False)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Transport"),
		},
		{
			ID:          "inject.cors.wildcard",
			Title:       "Wildcard CORS with credentials introduced",
			Message:     "The diff appears to combine a wildcard origin with credentialed requests.",
			Remediation: "Use an explicit origin allowlist when credentials are enabled for cross-origin requests.",
			Category:    "cors",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(credentials\s*[:=]\s*true|AllowCredentials\s*[:=]\s*true)`},
			Near:        []string{`(?i)(origin\s*[:=].*\*|Access-Control-Allow-Origin.*\*)`},
			Standards:   standard("OWASP-ASVS-V3.4", "OWASP-CORS"),
		},
		{
			ID:          "inject.logging.secret",
			Title:       "Sensitive data logging introduced",
			Message:     "The diff introduces debug or info logging around secrets, tokens, or credentials.",
			Remediation: "Remove sensitive values from logs and keep structured logging fields scrubbed by default.",
			Category:    "logging",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|print\(|console\.|logger\.).*(token|secret|password|authorization|cookie)`},
			Standards:   standard("OWASP-ASVS-V8", "OWASP-Logging"),
			Mask:        true,
		},
		{
			ID:          "inject.stacktrace",
			Title:       "Stack trace exposure introduced",
			Message:     "The diff exposes stack traces or raw exception details to clients.",
			Remediation: "Return generic client errors and keep stack traces in protected internal logs only.",
			Category:    "error",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(stacktrace|printStackTrace|traceback|err\.stack|debug\s*:\s*true)`},
			Standards:   standard("OWASP-ASVS-V10", "OWASP-Errors"),
		},
	}
}
