package rule

import "github.com/Pimatis/mavetis/src/model"

func inject() []model.Rule {
	return []model.Rule{
		{
			ID:          "inject.sql.raw",
			Title:       "Raw SQL query introduced",
			Message:     "The diff introduces string-built SQL that may bypass parameterization.",
			Remediation: "Use parameterized queries or prepared statements for dynamic SQL input.",
			Category:    "injection",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)\b(select\b.+\bfrom\b|insert\b.+\binto\b|update\b.+\bset\b|delete\b.+\bfrom\b).*(\+|fmt\.|sprintf|f"|\$\{|%s)`},
			Standards:   standard("OWASP-ASVS-V1.2", "OWASP-SQL"),
		},
		{
			ID:          "inject.command.exec",
			Title:       "Command execution introduced",
			Message:     "The diff introduces shell or command execution with probable untrusted input flow.",
			Remediation: "Avoid shell execution where possible and strictly separate arguments from user input.",
			Category:    "injection",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(exec\(|spawn\(|system\(|Runtime\.getRuntime\(|subprocess\.|sh\s+-c|bash\s+-c)`},
			Near:        []string{`(?i)(input|param|query|body|request|user|argv)`},
			Standards:   standard("OWASP-ASVS-V1.2", "OWASP-Injection"),
		},
		{
			ID:          "inject.ssrf.fetch",
			Title:       "External fetch based on untrusted input introduced",
			Message:     "The diff introduces a probable SSRF sink using untrusted URLs.",
			Remediation: "Resolve remote targets through a strict allowlist and block private, loopback, and metadata endpoints.",
			Category:    "ssrf",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(fetch\(|http\.Get\(|http\.Post\(|axios\.|requests\.(get|post)|urllib|urlopen\()`},
			Near:        []string{`(?i)(url|uri|target|endpoint|request|query|param|input)`},
			Absent:      []string{`(?i)(allowlist|whitelist|isAllowedHost|isTrustedHost|privateRange|linklocal|metadata|169\.254\.169\.254|127\.0\.0\.1|localhost)`},
			Standards:   standard("OWASP-ASVS-V4.3", "OWASP-SSRF"),
		},
		{
			ID:          "inject.xss.innerhtml",
			Title:       "Unsafe HTML sink introduced",
			Message:     "The diff introduces innerHTML or a comparable unsafe HTML rendering sink.",
			Remediation: "Use safe DOM APIs, context-aware encoding, or framework sanitization primitives.",
			Category:    "xss",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       webFiles(),
			Require:     []string{`(?i)(innerHTML|dangerouslySetInnerHTML|v-html|unsafeHTML)`},
			Standards:   standard("OWASP-ASVS-V3.2", "OWASP-XSS"),
		},
		{
			ID:          "inject.deserialize",
			Title:       "Unsafe deserialization introduced",
			Message:     "The diff introduces a deserialization flow that may trust attacker-controlled data.",
			Remediation: "Avoid native object deserialization for untrusted input and validate payload shape before use.",
			Category:    "deserialization",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(pickle\.loads|yaml\.load\(|gob\.NewDecoder|BinaryFormatter|deserialize\()`},
			Standards:   standard("OWASP-ASVS-V1.5", "OWASP-Deserialization"),
		},
		{
			ID:          "inject.traversal",
			Title:       "Path traversal risk introduced",
			Message:     "The diff introduces filesystem access using path fragments that may be attacker-controlled.",
			Remediation: "Normalize, bound, and validate filesystem paths before opening or writing files.",
			Category:    "file",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(ReadFile|WriteFile|os\.Open|os\.OpenFile|filepath\.Join|path\.Join|os\.Create)`},
			Near:        []string{`(?i)(\.\./|filename|filepath|path|request|query|param|input)`},
			Absent:      []string{`(?i)(filepath\.Clean|path\.Clean|filepath\.Base|safeJoin|EvalSymlinks)`},
			Standards:   standard("OWASP-ASVS-V5.4", "OWASP-File"),
		},
		{
			ID:          "inject.upload.validation",
			Title:       "File upload introduced without validation signals",
			Message:     "The diff introduces file upload handling without obvious content validation or storage controls.",
			Remediation: "Validate MIME type, extension, size, storage path, and scanning requirements before accepting uploads.",
			Category:    "file",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(multipart|FormFile|IFormFile|request\.files|UploadFile|ParseMultipartForm)`},
			Near:        []string{`(?i)(save|write|copy|store|upload)`},
			Absent:      []string{`(?i)(mime|content-type|extension|signature|magic|scan|sanitize|size\s*(limit|max)|maxUpload)`},
			Standards:   standard("OWASP-ASVS-V5.2", "OWASP-File"),
		},
		{
			ID:          "inject.tls.disable",
			Title:       "TLS verification disabled",
			Message:     "The diff disables TLS verification for outbound connections.",
			Remediation: "Keep TLS verification enabled and pin trust only when a documented exception exists.",
			Category:    "transport",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(InsecureSkipVerify\s*:\s*true|rejectUnauthorized\s*:\s*false|verify\s*=\s*False)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-Transport"),
		},
		{
			ID:          "inject.cors.wildcard",
			Title:       "Wildcard CORS with credentials introduced",
			Message:     "The diff appears to combine a wildcard origin with credentialed requests.",
			Remediation: "Use an explicit origin allowlist when credentials are enabled for cross-origin requests.",
			Category:    "cors",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(credentials\s*[:=]\s*true|AllowCredentials\s*[:=]\s*true)`},
			Near:        []string{`(?i)(origin\s*[:=].*\*|Access-Control-Allow-Origin.*\*)`},
			Standards:   standard("OWASP-ASVS-V3.4", "OWASP-CORS"),
		},
		{
			ID:          "inject.logging.secret",
			Title:       "Sensitive data logging introduced",
			Message:     "The diff introduces debug or info logging around secrets, tokens, or credentials.",
			Remediation: "Remove sensitive values from logs and keep structured logging fields scrubbed by default.",
			Category:    "logging",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|print\(|console\.|logger\.).*(token|secret|password|authorization|cookie)`},
			Standards:   standard("OWASP-ASVS-V8", "OWASP-Logging"),
			Mask:        true,
		},
		{
			ID:          "inject.stacktrace",
			Title:       "Stack trace exposure introduced",
			Message:     "The diff exposes stack traces or raw exception details to clients.",
			Remediation: "Return generic client errors and keep stack traces in protected internal logs only.",
			Category:    "error",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(stacktrace|printStackTrace|traceback|err\.stack|debug\s*:\s*true)`},
			Standards:   standard("OWASP-ASVS-V10", "OWASP-Errors"),
		},
		{
			ID:          "inject.redos",
			Title:       "Regular expression Denial of Service risk introduced",
			Message:     "The diff constructs or compiles a regular expression from request-controlled input without mitigation.",
			Remediation: "Avoid compiling regex from untrusted input, limit pattern length, or use a regex engine with ReDoS protection.",
			Category:    "injection",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(new RegExp\(|RegExp\(|re\.compile|regex\.compile|regexp\.compile|match\(|test\(|replace\()`},
			Near:        []string{`(?i)(input|param|query|body|request|user|req\.|ctx\.|params\.)`},
			Absent:      []string{`(?i)(maxLength|maxlen|limit|timeout|escapeRegex|sanitizeRegex)`},
			Standards:   standard("OWASP-ASVS-V5.1", "OWASP-ReDoS"),
		},
		{
			ID:          "inject.xml.xxee",
			Title:       "XML External Entity processing introduced",
			Message:     "The diff introduces XML parsing without disabling external entity resolution.",
			Remediation: "Disable DTDs and external entity resolution in XML parsers, or use a safer data format.",
			Category:    "injection",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(xml\.Unmarshal|xml\.Decoder|DocumentBuilder|SAXParser|XMLReader|new DOMParser|libxml2|xml\.etree\.ElementTree|lxml|parseXML|loadXML|fromXML)`},
			Near:        []string{`(?i)(parse|load|read|fromString|parseString|decode)`},
			Absent:      []string{`(?i)(resolve_entities\s*=\s*False|no_network|forbid_external|disable_dtd|setFeature.*EXTERNAL_ENTITY|setFeature.*DTD|expand_entities\s*=\s*False|noent|noxxee)`},
			Standards:   standard("OWASP-ASVS-V5.4", "OWASP-XXE"),
		},
		{
			ID:          "inject.openredirect",
			Title:       "Open redirect introduced",
			Message:     "The diff introduces a redirect that uses request-controlled destination data without validation.",
			Remediation: "Validate redirect destinations against a strict allowlist and reject arbitrary URLs.",
			Category:    "injection",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(redirect\(|location\s*=\s*|res\.redirect|response\.redirect|window\.location\s*=|header\(["']location["']|Location\s*:\s*|http\.Redirect)`},
			Near:        []string{`(?i)(query|param|input|request|req\.|ctx\.|params\.|url|uri|path|target)`},
			Absent:      []string{`(?i)(allowlist|whitelist|isTrustedUrl|validateRedirect|safeRedirect|isAllowedHost|trustedRedirect)`},
			Standards:   standard("OWASP-ASVS-V5.1", "OWASP-Redirect"),
		},
		{
			ID:          "inject.lfi",
			Title:       "Local File Inclusion introduced",
			Message:     "The diff includes or loads a file using a path that may be attacker-controlled.",
			Remediation: "Avoid including files based on user input and use a strict allowlist if dynamic inclusion is required.",
			Category:    "injection",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(include\(|require\(|include_once\(|require_once\(|import\s*\(|loadFile\(|load\()`},
			Near:        []string{`(?i)(filename|filepath|path|request|query|param|input|ctx\.|req\.|params\.|\$_GET|\$_POST|\$_REQUEST|\$_FILES)`},
			Absent:      []string{`(?i)(allowlist|whitelist|safePath|validateFile|allowedFiles)`},
			Standards:   standard("OWASP-ASVS-V12.3", "OWASP-LFI"),
		},
		{
			ID:          "inject.rfi",
			Title:       "Remote File Inclusion introduced",
			Message:     "The diff includes or loads a file from a remote or URL-controlled source.",
			Remediation: "Disable remote file inclusion and load only local trusted resources.",
			Category:    "injection",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(include\(|require\(|import\(|file_get_contents\(|readFile\(|fetch\(|http\.Get\()(\s*['"]?https?://|.*\$.*url|.*\$.*uri|.*\$.*remote)`},
			Standards:   standard("OWASP-ASVS-V12.3", "OWASP-RFI"),
		},
	}
}
