package rule

import "github.com/Pimatis/mavetis/src/model"

func logic() []model.Rule {
	return []model.Rule{
		{
			ID:          "logic.mass.assignment",
			Title:       "Mass assignment risk introduced",
			Message:     "The diff binds request-controlled input directly into a model or entity without field filtering.",
			Remediation: "Use explicit allowlists for assignable fields and avoid binding raw request bodies to internal models.",
			Category:    "logic",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(Object\.assign\(|\.assign\(|\.merge\(|create\(|update\(|save\(|insert\()`},
			Near:        []string{`(?i)(req\.body|request\.body|ctx\.request\.body|params\.|query\.|input\.)`},
			Absent:      []string{`(?i)(pick|select|whitelist|allowlist|permitted|fillable|guarded|validation|sanitize)`},
			Standards:   standard("OWASP-ASVS-V11.1", "OWASP-Business-Logic"),
		},
		{
			ID:          "logic.price.tampering",
			Title:       "Price or amount parameter tampering risk introduced",
			Message:     "The diff uses a request-controlled value for price, amount, or quantity without server-side verification.",
			Remediation: "Validate and recalculate price, total, and quantity on the server side and reject client-supplied monetary values.",
			Category:    "logic",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(price|amount|total|quantity|cost|fee|discount|tax).{0,20}(=|:).{0,20}(req\.|request\.|ctx\.|params\.|query\.|body\.|input\.|userInput)`},
			Absent:      []string{`(?i)(serverSide|recalculate|verifyPrice|validateAmount|checkTotal|computedPrice|lookupPrice)`},
			Standards:   standard("OWASP-ASVS-V11.1", "OWASP-Business-Logic"),
		},
		{
			ID:          "logic.negative.value",
			Title:       "Negative value accepted in financial field",
			Message:     "The diff accepts a negative value for price, amount, or quantity.",
			Remediation: "Reject negative values for price, amount, and quantity and enforce strict server-side validation.",
			Category:    "logic",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(price|amount|total|quantity|cost|fee|discount|tax).{0,20}(=|:).{0,20}[-]`},
			Absent:      []string{`(?i)(Math\.abs|abs\(|validate|sanitize|min.*0)`},
			Standards:   standard("OWASP-ASVS-V11.1", "OWASP-Business-Logic"),
		},
		{
			ID:          "logic.idempotency.missing",
			Title:       "Idempotency key missing for sensitive operation",
			Message:     "The diff introduces a payment, charge, or transfer without an idempotency key.",
			Remediation: "Require an idempotency key for all sensitive or financial operations.",
			Category:    "logic",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(payment|charge|transfer|withdraw|refund|invoice).{0,20}(create|process|execute|submit)`},
			Absent:      []string{`(?i)(idempotency|idempotencyKey|idempotent|empotency)`},
			Standards:   standard("OWASP-ASVS-V11.1", "OWASP-Business-Logic"),
		},
		{
			ID:          "api.pagination.missing",
			Title:       "Pagination limit missing on list query",
			Message:     "The diff introduces a list query without a pagination limit.",
			Remediation: "Enforce a default and maximum pagination limit on all list endpoints.",
			Category:    "logic",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(findAll|select\s*\*|query\(|getAll|listAll)`},
			Absent:      []string{`(?i)(limit|pageSize|maxResults|take|offset|page)`},
			Standards:   standard("OWASP-ASVS-V11.1", "OWASP-Business-Logic"),
		},
		{
			ID:          "api.bodysize.missing",
			Title:       "Request body size limit missing",
			Message:     "The diff introduces a request handler without a body size limit.",
			Remediation: "Set a strict maximum body size to prevent denial-of-service from oversized payloads.",
			Category:    "logic",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(bodyParser|parseBody|BodyParser|urlencoded|rawBody|json\.NewDecoder\(.*(r|req|request)\.Body|io\.ReadAll\(.*(r|req|request)\.Body)`},
			Absent:      []string{`(?i)(limit|maxBodySize|maxFileSize|bodyLimit)`},
			Standards:   standard("OWASP-ASVS-V11.1", "OWASP-Business-Logic"),
		},
	}
}
