package rule

import "github.com/Pimatis/mavetis/src/model"

func oauth() []model.Rule {
	return []model.Rule{
		{
			ID:          "auth.redirect.untrusted",
			Title:       "Untrusted redirect target introduced",
			Message:     "The diff introduces an OAuth, OIDC, or login redirect based on untrusted input.",
			Remediation: "Validate redirect targets against a strict allowlist before redirecting users.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(redirect|returnTo|callback|next).{0,20}(query|params|input|request|url)`},
			Near:        []string{`(?i)(oauth|oidc|login|signin|authorize|redirect)`},
			Absent:      []string{`(?i)(allowlist|whitelist|trustedRedirect|isAllowedRedirect|validateRedirect)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-OAuth"),
		},
		{
			ID:          "oauth.state.disabled",
			Title:       "OAuth state validation disabled",
			Message:     "The diff disables or bypasses OAuth state validation.",
			Remediation: "Keep state generation and validation enabled to defend authorization flows against CSRF and replay.",
			Category:    "auth",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(skipState(Check|Validation)?|disableState|state\s*[:=]\s*false|validateState\s*[:=]\s*false)`},
			Near:        []string{`(?i)(oauth|oidc|authorize|callback|login)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-OAuth"),
		},
		{
			ID:          "oauth.nonce.disabled",
			Title:       "OIDC nonce validation disabled",
			Message:     "The diff disables or bypasses nonce validation for an OIDC flow.",
			Remediation: "Validate nonce values on OIDC authorization responses and ID tokens.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(skipNonce(Check|Validation)?|disableNonce|nonce\s*[:=]\s*false|validateNonce\s*[:=]\s*false)`},
			Near:        []string{`(?i)(oidc|openid|id token|authorize|callback)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-OAuth"),
		},
		{
			ID:          "oauth.pkce.disabled",
			Title:       "PKCE protection disabled",
			Message:     "The diff disables PKCE or weakens the code challenge method for an OAuth flow.",
			Remediation: "Use PKCE with a strong verifier and keep code challenge validation enabled for public clients.",
			Category:    "auth",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(disablePKCE|skipPKCE|usePKCE\s*[:=]\s*false|code_challenge_method\s*[:=]\s*["']plain["'])`},
			Near:        []string{`(?i)(oauth|oidc|authorize|token|callback)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-OAuth"),
		},
		{
			ID:          "oauth.replay.deleted",
			Title:       "OAuth replay protection removed",
			Message:     "The diff removes a probable replay protection check for OAuth or OIDC artifacts.",
			Remediation: "Restore state, nonce, jti, or token binding verification before accepting the artifact.",
			Category:    "token",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(state|nonce|jti|replay|tokenBinding|proofOfPossession)`},
			Near:        []string{`(?i)(oauth|oidc|callback|token|id token|authorize)`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-OAuth"),
		},
	}
}
