package rule

import "github.com/Pimatis/mavetis/src/model"

func observe() []model.Rule {
	return []model.Rule{
		{
			ID:          "observe.request.body",
			Title:       "Request body logging introduced",
			Message:     "The diff logs request bodies or raw payloads, which can leak secrets and personal data.",
			Remediation: "Remove body logging or replace it with explicit field allowlists and redaction before emitting telemetry.",
			Category:    "logging",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|logger\.|console\.|print\(|fmt\.(Print|Printf)|zap\.|slog\.|trace\.|span\.).*(request\.body|req\.body|payload\b|ctx\.Body|RawBody|rawBody|bodyBytes)`},
			Standards:   standard("OWASP-ASVS-V8.1", "OWASP-Logging"),
			Mask:        true,
		},
		{
			ID:          "observe.auth.material",
			Title:       "Authentication material logged or traced",
			Message:     "The diff emits tokens, cookies, authorization headers, or sessions into logs or tracing fields.",
			Remediation: "Keep authentication material out of logs and traces, and emit only scrubbed identifiers when operationally required.",
			Category:    "logging",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|logger\.|console\.|print\(|fmt\.(Print|Printf)|zap\.|slog\.|trace\.|span\.).*(authorization|bearer|token|jwt|cookie|session(id)?|api[_-]?key|secret)`},
			Standards:   standard("OWASP-ASVS-V8.1", "OWASP-Logging"),
			Mask:        true,
		},
		{
			ID:          "observe.pii",
			Title:       "PII logging introduced",
			Message:     "The diff emits personal data such as email, phone, address, or national identifiers into telemetry.",
			Remediation: "Keep personal data out of logs and traces, or replace it with irreversible tokens and approved redaction.",
			Category:    "privacy",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|logger\.|console\.|print\(|fmt\.(Print|Printf)|zap\.|slog\.|trace\.|span\.).*(email|phone|mobile|address|ssn|nationalId|passport|sessionId|customerId)`},
			Standards:   standard("OWASP-ASVS-V8.1", "OWASP-Privacy"),
			Mask:        true,
		},
		{
			ID:          "observe.error.stringify",
			Title:       "Raw error object serialization introduced",
			Message:     "The diff serializes or prints full error objects, which can leak stack traces and hidden fields.",
			Remediation: "Log controlled error codes and approved summaries instead of stringifying or dumping full error objects.",
			Category:    "error",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(JSON\.stringify\(err(or)?\)|fmt\.(Sprintf|Printf)\(["'][^"']*%\+v[^"']*["'],\s*err(or)?\)|console\.(log|error)\(err(or)?\.(stack|message)\)|String\(err(or)?\))`},
			Standards:   standard("OWASP-ASVS-V10.3", "OWASP-Errors"),
		},
		{
			ID:          "observe.trace.sensitive",
			Title:       "Sensitive telemetry attribute introduced",
			Message:     "The diff adds sensitive security or personal fields to traces, spans, or analytics events.",
			Remediation: "Emit only approved low-sensitivity telemetry attributes and redact or hash security-sensitive fields before export.",
			Category:    "logging",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(setAttribute|SetAttributes|addEvent|track\(|capture\(|analytics\.|telemetry\.|span\.).*(token|authorization|cookie|session(id)?|email|phone|password|secret)`},
			Standards:   standard("OWASP-ASVS-V8.1", "OWASP-Logging"),
			Mask:        true,
		},
		{
			ID:          "observe.healthdata",
			Title:       "Health or medical data logged or traced",
			Message:     "The diff emits protected health information or medical identifiers into logs or traces.",
			Remediation: "Keep health data out of logs and traces, or replace it with approved pseudonymized identifiers.",
			Category:    "privacy",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(log\.|logger\.|console\.|print\(|fmt\.(Print|Printf)|zap\.|slog\.|trace\.|span\.).*(diagnosis|condition|treatment|medical|health|patient|mrn|medicalRecord|phi|hipaa|dob|bloodType|allergy|prescription|medication)`},
			Standards:   standard("OWASP-ASVS-V8.3", "OWASP-Privacy"),
			Mask:        true,
		},
	}
}
