package rule

import "github.com/Pimatis/mavetis/src/model"

func session() []model.Rule {
	return []model.Rule{
		{
			ID:          "session.cookie.secure",
			Title:       "Secure cookie flag downgraded",
			Message:     "The diff removes or disables the Secure cookie attribute.",
			Remediation: "Keep session cookies restricted to HTTPS by enforcing Secure for all authenticated cookies.",
			Category:    "session",
			Severity:    "high",
			Confidence:  "high",
			Target:      "any",
			Paths:       webAndConfigFiles(),
			Require:     []string{`(?i)(secure\s*[:=]\s*false|secure\s*[:=]\s*0|secure\s*[:=]\s*nil|secure\s*:\s*process\.env)`},
			Standards:   standard("OWASP-ASVS-V3.4", "OWASP-Session"),
		},
		{
			ID:          "session.cookie.httponly",
			Title:       "HttpOnly cookie flag downgraded",
			Message:     "The diff removes or disables the HttpOnly cookie attribute.",
			Remediation: "Enforce HttpOnly on session cookies to block script-level token access.",
			Category:    "session",
			Severity:    "high",
			Confidence:  "high",
			Target:      "any",
			Paths:       webAndConfigFiles(),
			Require:     []string{`(?i)(httpOnly\s*[:=]\s*false|httponly\s*[:=]\s*false)`},
			Standards:   standard("OWASP-ASVS-V3.4", "OWASP-Session"),
		},
		{
			ID:          "session.cookie.samesite",
			Title:       "SameSite cookie protection downgraded",
			Message:     "The diff weakens SameSite protection for cookies.",
			Remediation: "Use SameSite=Lax or SameSite=Strict for authenticated cookies unless a documented cross-site flow requires otherwise.",
			Category:    "session",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "any",
			Paths:       webAndConfigFiles(),
			Require:     []string{`(?i)(sameSite\s*[:=]\s*["']?none["']?|samesite=none)`},
			Standards:   standard("OWASP-ASVS-V3.4", "OWASP-Session"),
		},
		{
			ID:          "session.invalidation.deleted",
			Title:       "Session invalidation removed",
			Message:     "The diff removes a probable logout, revoke, or session invalidation call.",
			Remediation: "Restore session invalidation on logout, credential reset, and privilege changes.",
			Category:    "session",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(invalidate|revoke|destroySession|logoutAll|deleteSession|blacklist)`},
			Standards:   standard("OWASP-ASVS-V3.3", "OWASP-Session"),
		},
		{
			ID:          "session.regenerate.deleted",
			Title:       "Session rotation removed after authentication",
			Message:     "The diff removes a probable session rotation or regeneration step.",
			Remediation: "Rotate the session identifier after authentication and other privilege transitions to reduce fixation risk.",
			Category:    "session",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(regenerat|rotateSession|renewSession|changeSessionId|newSession|session\.Renew)`},
			Near:        []string{`(?i)(login|signin|auth|session|password|oauth)`},
			Standards:   standard("OWASP-ASVS-V3.3", "OWASP-Session"),
		},
		{
			ID:          "session.fixation.input",
			Title:       "Session identifier sourced from untrusted input",
			Message:     "The diff appears to source a session identifier directly from request-controlled input.",
			Remediation: "Generate server-side session identifiers and ignore untrusted session values supplied by clients.",
			Category:    "session",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(session(id)?|sid).{0,20}(query|params|header|cookie|request|ctx)`},
			Near:        []string{`(?i)(set|assign|create|login|signin|session)`},
			Absent:      []string{`(?i)(generate|random|uuid|newSession|regenerat|rotateSession)`},
			Standards:   standard("OWASP-ASVS-V3.3", "OWASP-Session"),
		},
		{
			ID:          "session.timeout.deleted",
			Title:       "Session timeout or expiry control removed",
			Message:     "The diff removes a probable session timeout, expiry, or TTL control.",
			Remediation: "Restore idle and absolute timeout controls for sessions and long-lived authentication tokens.",
			Category:    "session",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(maxAge|idleTimeout|sessionTimeout|expiresIn|expiration|expiry|ttl)`},
			Near:        []string{`(?i)(session|cookie|auth|token)`},
			Standards:   standard("OWASP-ASVS-V3.3", "OWASP-Session"),
		},
		{
			ID:          "session.token.singleuse.deleted",
			Title:       "Single-use token enforcement removed",
			Message:     "The diff removes a probable single-use invalidation path for reset, invite, or recovery tokens.",
			Remediation: "Keep reset and invitation tokens single-use and invalidate them immediately after successful redemption.",
			Category:    "token",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(consumeToken|markUsed|usedAt|consumedAt|invalidate.*token|delete.*token|revoke.*token)`},
			Near:        []string{`(?i)(reset|invite|recovery|magic.?link|verification)`},
			Standards:   standard("OWASP-ASVS-V3", "OWASP-Authentication"),
		},
	}
}
