package rule

import "github.com/Pimatis/mavetis/src/model"

func supply() []model.Rule {
	return []model.Rule{
		{
			ID:          "supply.workflow.secret",
			Title:       "CI workflow secret exposure introduced",
			Message:     "The diff appears to print or export secrets inside CI workflow definitions.",
			Remediation: "Keep CI secrets masked, avoid printing them, and scope them to the minimum required job.",
			Category:    "supply",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       workflowFiles(),
			Require:     []string{`(?i)(echo|print|export).*(secret|token|password|key)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-Secrets"),
			Mask:        true,
		},
		{
			ID:          "supply.postinstall",
			Title:       "Install-time script introduced",
			Message:     "The diff introduces an install-time script that can expand the supply-chain attack surface.",
			Remediation: "Avoid install hooks for untrusted dependencies and require code review for lifecycle scripts.",
			Category:    "supply",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       manifestFiles(),
			Require:     []string{`(?i)(postinstall|preinstall|prepare)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.remote.dependency",
			Title:       "Remote or git-based dependency source introduced",
			Message:     "The diff introduces a dependency pulled from a remote URL or mutable git reference.",
			Remediation: "Prefer registry releases with pinned versions and require extra review for direct git or URL dependencies.",
			Category:    "supply",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       manifestFiles(),
			Require:     []string{`(?i)(git\+https://|git\+ssh://|https://.+\.(tgz|zip)|github:|git@github\.com|@\s+git\+)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.lock.deleted",
			Title:       "Dependency lockfile removed",
			Message:     "The diff removes a dependency lockfile, which weakens deterministic builds and reviewability.",
			Remediation: "Keep lockfiles committed so dependency resolution stays reviewable and reproducible.",
			Category:    "supply",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "deleted",
			Paths:       []string{"**/go.sum", "**/package-lock.json", "**/bun.lockb", "**/bun.lock", "**/pnpm-lock.yaml", "**/yarn.lock", "**/Cargo.lock", "**/Pipfile.lock"},
			Require:     []string{`.+`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.integrity.deleted",
			Title:       "Dependency integrity hash removed",
			Message:     "The diff removes an integrity or resolved-hash field from a lockfile.",
			Remediation: "Preserve integrity metadata so package provenance and repeatability remain reviewable.",
			Category:    "supply",
			Severity:    "high",
			Confidence:  "high",
			Target:      "deleted",
			Paths:       []string{"**/package-lock.json", "**/pnpm-lock.yaml", "**/yarn.lock", "**/Pipfile.lock"},
			Require:     []string{`(?i)(integrity|resolved|sha512|sha256)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.exec.workflow",
			Title:       "Direct shell download execution introduced",
			Message:     "The diff introduces a shell pipeline that downloads and executes remote content.",
			Remediation: "Pin remote artifacts, verify integrity, and avoid piping network content directly into a shell.",
			Category:    "supply",
			Severity:    "critical",
			Confidence:  "high",
			Target:      "added",
			Paths:       append(workflowFiles(), "**/*.sh", "**/*.bash", "**/Dockerfile"),
			Require:     []string{`(?i)(curl|wget).*(\||>).*?(sh|bash|zsh)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.action.unpinned",
			Title:       "Mutable CI action reference introduced",
			Message:     "The diff references a mutable CI action tag such as main, master, or latest.",
			Remediation: "Pin CI actions to immutable commit SHAs or reviewed release tags.",
			Category:    "supply",
			Severity:    "medium",
			Confidence:  "high",
			Target:      "added",
			Paths:       workflowFiles(),
			Require:     []string{`(?i)uses:\s*[^@\s]+@(main|master|latest)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.workflow.permissions",
			Title:       "Overbroad workflow permissions introduced",
			Message:     "The diff grants write-all or similarly broad permissions to a CI workflow.",
			Remediation: "Reduce workflow permissions to the minimum required for the specific job.",
			Category:    "supply",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       workflowFiles(),
			Require:     []string{`(?i)(permissions:\s*write-all|contents:\s*write|packages:\s*write|id-token:\s*write)`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
		{
			ID:          "supply.workflow.pulltarget",
			Title:       "pull_request_target workflow introduced",
			Message:     "The diff introduces a pull_request_target trigger, which requires strict trust boundaries for untrusted code paths.",
			Remediation: "Use pull_request where possible and isolate privileged jobs from untrusted fork content.",
			Category:    "supply",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       workflowFiles(),
			Require:     []string{`(?i)pull_request_target`},
			Standards:   standard("OWASP-ASVS-V14", "OWASP-SupplyChain"),
		},
	}
}
