package rule

import "github.com/Pimatis/mavetis/src/model"

func websocket() []model.Rule {
	return []model.Rule{
		{
			ID:          "websocket.origin.missing",
			Title:       "WebSocket connection without origin validation",
			Message:     "The diff introduces a WebSocket upgrade or connection without Origin header verification.",
			Remediation: "Validate the Origin or Host header against an explicit allowlist before accepting WebSocket upgrade requests.",
			Category:    "websocket",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeAndConfigFiles(),
			Require:     []string{`(?i)(ws\.Upgrade|websocket\.Upgrade|WebSocket\(|new WebSocket|ws://|wss://|gorilla/websocket\.Upgrader|socket\.io\(|sockjs|ServerWebSocket|UseWebSockets)`},
			Absent:      []string{`(?i)(CheckOrigin|Origin\s*[:=]|origin\s*[:=]|AllowedOrigins|allowedOrigins|Host\s*[:=]|host\s*[:=])`},
			Standards:   standard("OWASP-ASVS-V4.1", "OWASP-WebSocket"),
		},
		{
			ID:          "websocket.downgrade.missing",
			Title:       "WebSocket connection without TLS enforcement",
			Message:     "The diff introduces a WebSocket connection using plain ws:// without enforcing wss:// upgrade.",
			Remediation: "Reject plain ws:// connections in production and enforce wss:// for all WebSocket traffic.",
			Category:    "websocket",
			Severity:    "high",
			Confidence:  "high",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(ws://|"ws://|'ws://|` + "`" + `ws://|connect\(\s*["']ws)`},
			Absent:      []string{`(?i)(localhost|127\.0\.0\.1|wss://|isSecure|secure\s*[:=]\s*true|tlsconfig|TLSConfig)`},
			Standards:   standard("OWASP-ASVS-V9.1", "OWASP-ASVS-V3.4", "OWASP-WebSocket"),
		},
		{
			ID:          "websocket.message.validation.missing",
			Title:       "WebSocket message without validation",
			Message:     "The diff introduces WebSocket message handling without schema validation or content checks.",
			Remediation: "Validate incoming WebSocket messages against a strict schema and reject malformed or oversized payloads.",
			Category:    "websocket",
			Severity:    "high",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(OnMessage|onmessage|ws\.ReadMessage|websocket\.ReadMessage|conn\.ReadMessage|ReadMessage|conn\.ReadJSON|socket\.on\(|ws\.on\()`},
			Absent:      []string{`(?i)(validate|Validate|schema|Schema|must|Must|assert|Assert|check|Check|typeguard|TypeGuard|zod|yup|joi|ajv|class.validator|maxSize|maxlength|limit)`},
			Standards:   standard("OWASP-ASVS-V1.5", "OWASP-ASVS-V5.1", "OWASP-WebSocket"),
		},
		{
			ID:          "websocket.auth.missing",
			Title:       "WebSocket upgrade without authentication",
			Message:     "The diff introduces a WebSocket upgrade or handler without nearby authentication or authorization checks.",
			Remediation: "Authenticate WebSocket connections via token, cookie, or sub-protocol before accepting the upgrade.",
			Category:    "websocket",
			Severity:    "critical",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(ws\.Upgrade|websocket\.Upgrade|gorilla/websocket\.Upgrader|socket\.io\(|socketio\.|handleWebSocket|UseWebSockets|WebSocketHandler)`},
			Absent:      []string{`(?i)(auth|Auth|token|Token|jwt|JWT|session|Session|cookie|Cookie|bearer|Bearer|verifyAuth|requireAuth|authenticate|authorize|middleware)`},
			Standards:   standard("OWASP-ASVS-V3.1", "OWASP-ASVS-V4.1", "OWASP-WebSocket"),
		},
		{
			ID:          "websocket.ratelimit.missing",
			Title:       "WebSocket connection without rate limiting",
			Message:     "The diff introduces WebSocket handling without per-connection message rate or count limits.",
			Remediation: "Enforce per-connection message rate limits and maximum concurrent WebSocket connection counts.",
			Category:    "websocket",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(ws\.Upgrade|websocket\.Upgrade|WebSocket\(|gorilla/websocket\.Upgrader|socket\.io\(|handleWebSocket|ws\.Handle\()`},
			Absent:      []string{`(?i)(rate|Rate|throttle|Throttle|backoff|Backoff|limit|Limit|maxConn|MaxConn|max.*connect|quot|Quota)`},
			Standards:   standard("OWASP-ASVS-V7.2", "OWASP-WebSocket"),
		},
		{
			ID:          "websocket.ping.missing",
			Title:       "WebSocket heartbeat missing",
			Message:     "The diff introduces a WebSocket handler without ping/pong or keepalive.",
			Remediation: "Implement periodic ping/pong or keepalive to detect and close stale connections.",
			Category:    "websocket",
			Severity:    "medium",
			Confidence:  "medium",
			Target:      "added",
			Paths:       codeFiles(),
			Require:     []string{`(?i)(ws\.Upgrade|websocket\.Upgrade|WebSocket\(|gorilla/websocket\.Upgrader|socket\.io\(|handleWebSocket|ws\.Handle\()`},
			Absent:      []string{`(?i)(ping|pong|keepalive|keepAlive|heartbeat|HeartBeat)`},
			Standards:   standard("OWASP-ASVS-V7.2", "OWASP-WebSocket"),
		},
	}
}
